import json
import os

# Base directory for specs
SPEC_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "specs"))
os.makedirs(SPEC_DIR, exist_ok=True)

# -------------------------------------------------------------
# 1. CLUSTERS (Domain Pillows)
# -------------------------------------------------------------
clusters = [
    {
        "id": "c_acc",
        "title": "1. PHÂN HỆ TÀI KHOẢN, KHÁCH HÀNG & SỨC KHỎE",
        "x": 60,
        "y": 60,
        "width": 1190,
        "height": 990,
        "bg_color": "#F8FAFC",
        "border_color": "#CBD5E1",
        "title_color": "#1E293B",
        "visible": False,
    },
    {
        "id": "c_cart",
        "title": "2. PHÂN HỆ GIỎ HÀNG, HÓA ĐƠN & GỢI Ý MÓN ĂN",
        "x": 1310,
        "y": 60,
        "width": 1210,
        "height": 990,
        "bg_color": "#F0FDF4",
        "border_color": "#BBF7D0",
        "title_color": "#166534",
        "visible": False,
    },
    {
        "id": "c_prod",
        "title": "3. PHÂN HỆ DANH MỤC & THÔNG TIN SẢN PHẨM",
        "x": 2580,
        "y": 60,
        "width": 1190,
        "height": 990,
        "bg_color": "#EFF6FF",
        "border_color": "#BFDBFE",
        "title_color": "#1E40AF",
        "visible": False,
    },
    {
        "id": "c_store",
        "title": "4. PHÂN HỆ BỐ TRÍ MẶT BẰNG & VỊ TRÍ KỆ HÀNG",
        "x": 60,
        "y": 1180,
        "width": 1190,
        "height": 1150,
        "bg_color": "#FFFBEB",
        "border_color": "#FDE68A",
        "title_color": "#92400E",
        "visible": False,
    },
    {
        "id": "c_slam",
        "title": "5. PHÂN HỆ ĐIỀU HƯỚNG ROBOT & QUÉT BẢN ĐỒ SLAM",
        "x": 1310,
        "y": 1180,
        "width": 1210,
        "height": 1150,
        "bg_color": "#FDF4FF",
        "border_color": "#F0ABFC",
        "title_color": "#86198F",
        "visible": False,
    },
    {
        "id": "c_mkt",
        "title": "6. PHÂN HỆ QUẢNG CÁO & TIẾP THỊ THƯƠNG HIỆU",
        "x": 2580,
        "y": 1180,
        "width": 1190,
        "height": 1150,
        "bg_color": "#FFF1F2",
        "border_color": "#FECDD3",
        "title_color": "#9F1239",
        "visible": False,
    },
]

# -------------------------------------------------------------
# 2. NODES (34 Tables with exact columns and layout coordinates)
# -------------------------------------------------------------
nodes = [
    # --- Cluster 1: Account & Health ---
    {
        "id": "ACCOUNT",
        "x": 100,
        "y": 140,
        "width": 260,
        "columns": [
            {"name": "AccountID", "type": "int", "is_pk": True},
            {"name": "Username", "type": "string"},
            {"name": "PasswordHash", "type": "string"},
            {"name": "Email", "type": "string"},
            {"name": "FullName", "type": "string"},
            {"name": "Role", "type": "string"},
            {"name": "Status", "type": "string"},
        ],
    },
    {
        "id": "MEMBER",
        "x": 480,
        "y": 140,
        "width": 270,
        "columns": [
            {"name": "MemberID", "type": "int", "is_pk": True},
            {"name": "AccountID", "type": "int", "is_fk": True},
            {"name": "FullName", "type": "string"},
            {"name": "FaceVector", "type": "string", "is_nullable": True},
            {"name": "SpendingLimit", "type": "decimal", "is_nullable": True},
            {"name": "TotalPoints", "type": "int"},
        ],
    },
    {
        "id": "MEMBERSHIP",
        "x": 870,
        "y": 140,
        "width": 260,
        "columns": [
            {"name": "MembershipID", "type": "int", "is_pk": True},
            {"name": "MemberID", "type": "int", "is_fk": True},
            {"name": "TierName", "type": "string"},
            {"name": "Status", "type": "string"},
        ],
    },
    {
        "id": "HEALTH_TAG",
        "x": 100,
        "y": 480,
        "width": 260,
        "columns": [
            {"name": "HealthTagID", "type": "int", "is_pk": True},
            {"name": "TagName", "type": "string"},
            {"name": "TagType", "type": "string"},
        ],
    },
    {
        "id": "MEMBERHEALTH_PREFERENCE",
        "x": 480,
        "y": 480,
        "width": 290,
        "columns": [
            {"name": "MemberID", "type": "int", "is_pk": True, "is_fk": True},
            {"name": "HealthTagID", "type": "int", "is_pk": True, "is_fk": True},
            {"name": "status", "type": "string"},
        ],
    },
    {
        "id": "MEMBER_NOTIFICATION",
        "x": 870,
        "y": 480,
        "width": 270,
        "columns": [
            {"name": "NotificationID", "type": "int", "is_pk": True},
            {"name": "MemberID", "type": "int", "is_fk": True},
            {"name": "NotifType", "type": "string"},
            {"name": "Title", "type": "string"},
            {"name": "IsRead", "type": "boolean"},
        ],
    },

    # --- Cluster 2: Cart & Invoice & Meal ---
    {
        "id": "CART",
        "x": 1360,
        "y": 140,
        "width": 260,
        "columns": [
            {"name": "CartID", "type": "int", "is_pk": True},
            {"name": "MemberID", "type": "int", "is_fk": True},
            {"name": "CreatedAt", "type": "datetime"},
        ],
    },
    {
        "id": "CART_ITEM",
        "x": 1730,
        "y": 140,
        "width": 260,
        "columns": [
            {"name": "CartItemID", "type": "int", "is_pk": True},
            {"name": "CartID", "type": "int", "is_fk": True},
            {"name": "ProductID", "type": "int", "is_fk": True},
            {"name": "Quantity", "type": "int"},
        ],
    },
    {
        "id": "MEAL_SUGGESTION",
        "x": 2110,
        "y": 140,
        "width": 280,
        "columns": [
            {"name": "MealSuggestionID", "type": "int", "is_pk": True},
            {"name": "MealName", "type": "string"},
            {"name": "Calories", "type": "int"},
            {"name": "healthy_score", "type": "int"},
        ],
    },
    {
        "id": "INVOICE_HISTORY",
        "x": 1360,
        "y": 460,
        "width": 260,
        "columns": [
            {"name": "InvoiceHistoryID", "type": "int", "is_pk": True},
            {"name": "MemberID", "type": "int", "is_fk": True},
            {"name": "PurchaseDate", "type": "datetime"},
            {"name": "TotalPrice", "type": "decimal"},
        ],
    },
    {
        "id": "INVOICE_HISTORY_ITEM",
        "x": 1730,
        "y": 460,
        "width": 270,
        "columns": [
            {"name": "InvoiceHistoryItemID", "type": "int", "is_pk": True},
            {"name": "InvoiceHistoryID", "type": "int", "is_fk": True},
            {"name": "ProductID", "type": "int", "is_fk": True},
            {"name": "Quantity", "type": "int"},
            {"name": "UnitPrice", "type": "decimal"},
        ],
    },
    {
        "id": "MEAL_ITEM",
        "x": 2110,
        "y": 460,
        "width": 270,
        "columns": [
            {"name": "MealSuggestionID", "type": "int", "is_pk": True, "is_fk": True},
            {"name": "ProductID", "type": "int", "is_pk": True, "is_fk": True},
            {"name": "QuantityRequired", "type": "decimal"},
        ],
    },

    # --- Cluster 3: Catalog & Products ---
    {
        "id": "CATEGORY",
        "x": 2630,
        "y": 140,
        "width": 240,
        "columns": [
            {"name": "CategoryID", "type": "int", "is_pk": True},
            {"name": "CategoryName", "type": "string"},
        ],
    },
    {
        "id": "SUBCATEGORY",
        "x": 2980,
        "y": 140,
        "width": 250,
        "columns": [
            {"name": "SubcategoryID", "type": "int", "is_pk": True},
            {"name": "CategoryID", "type": "int", "is_fk": True},
            {"name": "SubcategoryName", "type": "string"},
        ],
    },
    {
        "id": "PRODUCT_TYPE",
        "x": 3340,
        "y": 140,
        "width": 250,
        "columns": [
            {"name": "ProductTypeID", "type": "int", "is_pk": True},
            {"name": "SubcategoryID", "type": "int", "is_fk": True},
            {"name": "TypeName", "type": "string"},
        ],
    },
    {
        "id": "PRODUCT",
        "x": 2840,
        "y": 440,
        "width": 280,
        "columns": [
            {"name": "ProductID", "type": "int", "is_pk": True},
            {"name": "ProductTypeID", "type": "int", "is_fk": True},
            {"name": "ProductName", "type": "string"},
            {"name": "UnitPrice", "type": "decimal"},
            {"name": "PromotionPrice", "type": "decimal", "is_nullable": True},
            {"name": "Status", "type": "string"},
        ],
    },
    {
        "id": "PRODUCT_HEALTHTAG",
        "x": 3280,
        "y": 440,
        "width": 270,
        "columns": [
            {"name": "ProductID", "type": "int", "is_pk": True, "is_fk": True},
            {"name": "HealthTagID", "type": "int", "is_pk": True, "is_fk": True},
        ],
    },

    # --- Cluster 4: Supermarket Floor Layout ---
    {
        "id": "FLOOR",
        "x": 100,
        "y": 1260,
        "width": 240,
        "columns": [
            {"name": "FloorID", "type": "int", "is_pk": True},
            {"name": "FloorNumber", "type": "int"},
        ],
    },
    {
        "id": "ZONE",
        "x": 450,
        "y": 1260,
        "width": 250,
        "columns": [
            {"name": "ZoneID", "type": "int", "is_pk": True},
            {"name": "FloorID", "type": "int", "is_fk": True},
            {"name": "ZoneName", "type": "string"},
        ],
    },
    {
        "id": "AISLE",
        "x": 800,
        "y": 1260,
        "width": 260,
        "columns": [
            {"name": "AisleID", "type": "int", "is_pk": True},
            {"name": "ZoneID", "type": "int", "is_fk": True},
            {"name": "AisleCode", "type": "string"},
            {"name": "AisleName", "type": "string"},
        ],
    },
    {
        "id": "SHELF",
        "x": 800,
        "y": 1560,
        "width": 260,
        "columns": [
            {"name": "ShelfID", "type": "int", "is_pk": True},
            {"name": "AisleID", "type": "int", "is_fk": True},
            {"name": "LevelNumber", "type": "int"},
        ],
    },
    {
        "id": "SLOT",
        "x": 800,
        "y": 1860,
        "width": 260,
        "columns": [
            {"name": "SlotID", "type": "int", "is_pk": True},
            {"name": "ShelfID", "type": "int", "is_fk": True},
            {"name": "SlotCode", "type": "string"},
            {"name": "Quantity", "type": "int"},
        ],
    },
    {
        "id": "PRODUCT_SLOT",
        "x": 440,
        "y": 1860,
        "width": 260,
        "columns": [
            {"name": "ProductSlotID", "type": "int", "is_pk": True},
            {"name": "SlotID", "type": "int", "is_fk": True},
            {"name": "ProductID", "type": "int", "is_fk": True},
        ],
    },

    # --- Cluster 5: Robot & SLAM Navigation ---
    {
        "id": "MAP",
        "x": 1360,
        "y": 1260,
        "width": 260,
        "columns": [
            {"name": "MapID", "type": "int", "is_pk": True},
            {"name": "FloorID", "type": "int", "is_fk": True},
            {"name": "MapName", "type": "string"},
            {"name": "MapData", "type": "string"},
        ],
    },
    {
        "id": "NAVIGATION_NODE",
        "x": 1720,
        "y": 1260,
        "width": 280,
        "columns": [
            {"name": "NodeID", "type": "int", "is_pk": True},
            {"name": "MapID", "type": "int", "is_fk": True},
            {"name": "NodeName", "type": "string"},
            {"name": "XCoord", "type": "float"},
            {"name": "YCoord", "type": "float"},
            {"name": "NodeType", "type": "string"},
        ],
    },
    {
        "id": "NAVIGATION_EDGE",
        "x": 2100,
        "y": 1260,
        "width": 270,
        "columns": [
            {"name": "EdgeID", "type": "int", "is_pk": True},
            {"name": "FromNodeID", "type": "int", "is_fk": True},
            {"name": "ToNodeID", "type": "int", "is_fk": True},
            {"name": "Distance", "type": "float"},
        ],
    },
    {
        "id": "ROBOT",
        "x": 1360,
        "y": 1580,
        "width": 260,
        "columns": [
            {"name": "RobotID", "type": "int", "is_pk": True},
            {"name": "RobotName", "type": "string"},
            {"name": "RobotCode", "type": "string"},
            {"name": "BatteryPct", "type": "int"},
            {"name": "Mode", "type": "string"},
            {"name": "Status", "type": "string"},
        ],
    },
    {
        "id": "AISLE_SCAN",
        "x": 1720,
        "y": 1580,
        "width": 280,
        "columns": [
            {"name": "ScanID", "type": "int", "is_pk": True},
            {"name": "AisleID", "type": "int", "is_fk": True},
            {"name": "RobotID", "type": "int", "is_fk": True},
            {"name": "EmptyPercentage", "type": "decimal"},
            {"name": "DensityPercentage", "type": "decimal"},
            {"name": "NeedsRestock", "type": "boolean"},
        ],
    },
    {
        "id": "ROBOT_LOG",
        "x": 1360,
        "y": 1920,
        "width": 260,
        "columns": [
            {"name": "LogID", "type": "int", "is_pk": True},
            {"name": "RobotID", "type": "int", "is_fk": True},
            {"name": "Battery", "type": "int"},
            {"name": "Location", "type": "string"},
            {"name": "Status", "type": "string"},
        ],
    },
    {
        "id": "SEMANTIC_OBJECT",
        "x": 1720,
        "y": 1920,
        "width": 280,
        "columns": [
            {"name": "ObjectID", "type": "int", "is_pk": True},
            {"name": "MapID", "type": "int", "is_fk": True},
            {"name": "ObjectType", "type": "string"},
            {"name": "ProductID", "type": "int", "is_nullable": True},
            {"name": "Label", "type": "string"},
        ],
    },

    # --- Cluster 6: Marketing & Campaigns ---
    {
        "id": "BRAND",
        "x": 2630,
        "y": 1260,
        "width": 250,
        "columns": [
            {"name": "BrandID", "type": "int", "is_pk": True},
            {"name": "BrandName", "type": "string"},
            {"name": "IsSystemBrand", "type": "boolean"},
        ],
    },
    {
        "id": "AD_PACKAGE",
        "x": 2980,
        "y": 1260,
        "width": 270,
        "columns": [
            {"name": "PackageID", "type": "int", "is_pk": True},
            {"name": "PackageName", "type": "string"},
            {"name": "Budget", "type": "decimal"},
            {"name": "ZoneFee", "type": "decimal"},
            {"name": "ShelfFee", "type": "decimal"},
            {"name": "DurationDays", "type": "int"},
            {"name": "Status", "type": "string"},
        ],
    },
    {
        "id": "AD_CAMPAIGN",
        "x": 3350,
        "y": 1260,
        "width": 280,
        "columns": [
            {"name": "AdCampaignID", "type": "int", "is_pk": True},
            {"name": "PackageID", "type": "int", "is_fk": True},
            {"name": "BrandID", "type": "int", "is_fk": True},
            {"name": "SemanticObjectID", "type": "int", "is_fk": True, "is_nullable": True},
            {"name": "CampaignName", "type": "string"},
            {"name": "StartDate", "type": "datetime"},
            {"name": "EndDate", "type": "datetime"},
            {"name": "Status", "type": "string"},
        ],
    },
    {
        "id": "SPONSORED_PRODUCT",
        "x": 2980,
        "y": 1620,
        "width": 270,
        "columns": [
            {"name": "SponsoredID", "type": "int", "is_pk": True},
            {"name": "AdCampaignID", "type": "int", "is_fk": True},
            {"name": "ProductID", "type": "int", "is_fk": True},
            {"name": "Priority", "type": "int"},
            {"name": "status", "type": "string"},
        ],
    },
    {
        "id": "AD_RESOURCE",
        "x": 3350,
        "y": 1620,
        "width": 280,
        "columns": [
            {"name": "ResourceID", "type": "int", "is_pk": True},
            {"name": "AdCampaignID", "type": "int", "is_fk": True},
            {"name": "ResourceType", "type": "string"},
            {"name": "ResourceURL", "type": "string"},
            {"name": "Status", "type": "string"},
        ],
    },
    {
        "id": "AD_CAMPAIGN_LOG",
        "x": 2980,
        "y": 1940,
        "width": 280,
        "columns": [
            {"name": "LogID", "type": "int", "is_pk": True},
            {"name": "AdCampaignID", "type": "int", "is_fk": True},
            {"name": "ActionType", "type": "string"},
            {"name": "ChargedAmount", "type": "decimal"},
            {"name": "ProductID", "type": "int", "is_nullable": True},
            {"name": "RobotID", "type": "int", "is_nullable": True},
            {"name": "ZoneID", "type": "int", "is_nullable": True},
            {"name": "MemberID", "type": "int", "is_nullable": True},
        ],
    },
]

# -------------------------------------------------------------
# 3. CONNECTIONS (39 relationships with ports, cardinalities, waypoints)
# -------------------------------------------------------------
connections = [
    # Cluster 1: Account & Health
    {
        "source": "ACCOUNT",
        "target": "MEMBER",
        "source_port": "right",
        "target_port": "left",
        "cardinality_source": "||",
        "cardinality_target": "o|",
        "label_pos": 0.5,
        "corner_radius": 8.0,
    },
    {
        "source": "MEMBER",
        "target": "MEMBERSHIP",
        "source_port": "right",
        "target_port": "left",
        "cardinality_source": "||",
        "cardinality_target": "o{",
        "label_pos": 0.5,
        "corner_radius": 8.0,
    },
    {
        "source": "HEALTH_TAG",
        "target": "MEMBERHEALTH_PREFERENCE",
        "source_port": "right",
        "target_port": "left",
        "cardinality_source": "||",
        "cardinality_target": "o{",
        "label_pos": 0.5,
        "corner_radius": 8.0,
    },
    {
        "source": "MEMBER",
        "target": "MEMBERHEALTH_PREFERENCE",
        "source_port": "bottom",
        "target_port": "top",
        "cardinality_source": "||",
        "cardinality_target": "o{",
        "label_pos": 0.5,
        "corner_radius": 8.0,
    },
    {
        "source": "MEMBER",
        "target": "MEMBER_NOTIFICATION",
        "source_port": "bottom",
        "target_port": "top",
        "source_offset": 50.0,
        "target_offset": -40.0,
        "cardinality_source": "||",
        "cardinality_target": "o{",
        "label_pos": 0.5,
        "waypoints": [[665, 380], [965, 380]],
        "corner_radius": 10.0,
    },

    # Cross: Member -> Cart & Invoices
    {
        "source": "MEMBER",
        "target": "CART",
        "source_port": "top",
        "target_port": "top",
        "cardinality_source": "||",
        "cardinality_target": "o{",
        "label_pos": 0.5,
        "waypoints": [[615, 95], [1490, 95]],
        "corner_radius": 12.0,
    },
    {
        "source": "MEMBER",
        "target": "INVOICE_HISTORY",
        "source_port": "bottom",
        "target_port": "left",
        "source_offset": -40.0,
        "cardinality_source": "||",
        "cardinality_target": "o{",
        "label_pos": 0.5,
        "waypoints": [[575, 400], [1270, 400], [1270, 535]],
        "corner_radius": 10.0,
    },

    # Cluster 2: Cart & Invoice & Meal
    {
        "source": "CART",
        "target": "CART_ITEM",
        "source_port": "right",
        "target_port": "left",
        "cardinality_source": "||",
        "cardinality_target": "o{",
        "label_pos": 0.5,
        "corner_radius": 8.0,
    },
    {
        "source": "INVOICE_HISTORY",
        "target": "INVOICE_HISTORY_ITEM",
        "source_port": "right",
        "target_port": "left",
        "cardinality_source": "||",
        "cardinality_target": "}|",
        "label_pos": 0.5,
        "corner_radius": 8.0,
    },
    {
        "source": "MEAL_SUGGESTION",
        "target": "MEAL_ITEM",
        "source_port": "bottom",
        "target_port": "top",
        "cardinality_source": "||",
        "cardinality_target": "}|",
        "label_pos": 0.5,
        "corner_radius": 8.0,
    },
    {
        "source": "PRODUCT",
        "target": "MEAL_ITEM",
        "source_port": "left",
        "target_port": "right",
        "source_offset": 30.0,
        "cardinality_source": "||",
        "cardinality_target": "o{",
        "label_pos": 0.5,
        "waypoints": [[2500, 570], [2500, 525]],
        "corner_radius": 10.0,
    },
    {
        "source": "PRODUCT",
        "target": "INVOICE_HISTORY_ITEM",
        "source_port": "left",
        "target_port": "right",
        "source_offset": -30.0,
        "cardinality_source": "||",
        "cardinality_target": "o{",
        "label_pos": 0.5,
        "waypoints": [[2500, 510], [2500, 545]],
        "corner_radius": 10.0,
    },
    {
        "source": "PRODUCT",
        "target": "CART_ITEM",
        "source_port": "top",
        "target_port": "right",
        "cardinality_source": "||",
        "cardinality_target": "o{",
        "label_pos": 0.5,
        "waypoints": [[2980, 390], [2050, 390], [2050, 215]],
        "corner_radius": 12.0,
    },

    # Cluster 3: Catalog & Products
    {
        "source": "CATEGORY",
        "target": "SUBCATEGORY",
        "source_port": "right",
        "target_port": "left",
        "cardinality_source": "||",
        "cardinality_target": "o{",
        "label_pos": 0.5,
        "corner_radius": 8.0,
    },
    {
        "source": "SUBCATEGORY",
        "target": "PRODUCT_TYPE",
        "source_port": "right",
        "target_port": "left",
        "cardinality_source": "||",
        "cardinality_target": "o{",
        "label_pos": 0.5,
        "corner_radius": 8.0,
    },
    {
        "source": "PRODUCT_TYPE",
        "target": "PRODUCT",
        "source_port": "bottom",
        "target_port": "top",
        "source_offset": -30.0,
        "target_offset": 40.0,
        "cardinality_source": "||",
        "cardinality_target": "o{",
        "label_pos": 0.5,
        "waypoints": [[3435, 360], [3020, 360]],
        "corner_radius": 10.0,
    },
    {
        "source": "PRODUCT",
        "target": "PRODUCT_HEALTHTAG",
        "source_port": "right",
        "target_port": "left",
        "cardinality_source": "||",
        "cardinality_target": "o{",
        "label_pos": 0.5,
        "corner_radius": 8.0,
    },
    {
        "source": "HEALTH_TAG",
        "target": "PRODUCT_HEALTHTAG",
        "source_port": "bottom",
        "target_port": "bottom",
        "cardinality_source": "||",
        "cardinality_target": "o{",
        "label_pos": 0.5,
        "waypoints": [[230, 980], [3415, 980]],
        "corner_radius": 14.0,
    },

    # Cluster 4: Supermarket Floor Layout
    {
        "source": "FLOOR",
        "target": "ZONE",
        "source_port": "right",
        "target_port": "left",
        "cardinality_source": "||",
        "cardinality_target": "o{",
        "label_pos": 0.5,
        "corner_radius": 8.0,
    },
    {
        "source": "ZONE",
        "target": "AISLE",
        "source_port": "right",
        "target_port": "left",
        "cardinality_source": "||",
        "cardinality_target": "o{",
        "label_pos": 0.5,
        "corner_radius": 8.0,
    },
    {
        "source": "AISLE",
        "target": "SHELF",
        "source_port": "bottom",
        "target_port": "top",
        "cardinality_source": "||",
        "cardinality_target": "o{",
        "label_pos": 0.5,
        "corner_radius": 8.0,
    },
    {
        "source": "SHELF",
        "target": "SLOT",
        "source_port": "bottom",
        "target_port": "top",
        "cardinality_source": "||",
        "cardinality_target": "o{",
        "label_pos": 0.5,
        "corner_radius": 8.0,
    },
    {
        "source": "SLOT",
        "target": "PRODUCT_SLOT",
        "source_port": "left",
        "target_port": "right",
        "cardinality_source": "||",
        "cardinality_target": "o{",
        "label_pos": 0.5,
        "corner_radius": 8.0,
    },
    {
        "source": "PRODUCT",
        "target": "PRODUCT_SLOT",
        "source_port": "bottom",
        "target_port": "bottom",
        "source_offset": -80.0,
        "cardinality_source": "||",
        "cardinality_target": "o{",
        "label_pos": 0.5,
        "waypoints": [[2860, 1110], [570, 1110], [570, 2040]],
        "corner_radius": 14.0,
    },

    # Cluster 5: Robot & SLAM Navigation
    {
        "source": "FLOOR",
        "target": "MAP",
        "source_port": "top",
        "target_port": "left",
        "cardinality_source": "||",
        "cardinality_target": "o|",
        "label_pos": 0.5,
        "waypoints": [[220, 1220], [1300, 1220], [1300, 1335]],
        "corner_radius": 12.0,
    },
    {
        "source": "MAP",
        "target": "NAVIGATION_NODE",
        "source_port": "right",
        "target_port": "left",
        "cardinality_source": "||",
        "cardinality_target": "}|",
        "label_pos": 0.5,
        "corner_radius": 8.0,
    },
    {
        "source": "NAVIGATION_NODE",
        "target": "NAVIGATION_EDGE",
        "source_port": "right",
        "target_port": "left",
        "cardinality_source": "||",
        "cardinality_target": "o{",
        "label_pos": 0.5,
        "corner_radius": 8.0,
    },
    {
        "source": "ROBOT",
        "target": "ROBOT_LOG",
        "source_port": "bottom",
        "target_port": "top",
        "cardinality_source": "||",
        "cardinality_target": "o{",
        "label_pos": 0.5,
        "corner_radius": 8.0,
    },
    {
        "source": "AISLE",
        "target": "AISLE_SCAN",
        "source_port": "right",
        "target_port": "left",
        "cardinality_source": "||",
        "cardinality_target": "o{",
        "label_pos": 0.5,
        "waypoints": [[1130, 1335], [1130, 1670]],
        "corner_radius": 10.0,
    },
    {
        "source": "ROBOT",
        "target": "AISLE_SCAN",
        "source_port": "right",
        "target_port": "left",
        "cardinality_source": "||",
        "cardinality_target": "o{",
        "label_pos": 0.5,
        "corner_radius": 8.0,
    },
    {
        "source": "MAP",
        "target": "SEMANTIC_OBJECT",
        "source_port": "bottom",
        "target_port": "top",
        "source_offset": 50.0,
        "target_offset": -40.0,
        "cardinality_source": "||",
        "cardinality_target": "o{",
        "label_pos": 0.5,
        "waypoints": [[1540, 1780], [1820, 1780]],
        "corner_radius": 10.0,
    },
    {
        "source": "PRODUCT",
        "target": "SEMANTIC_OBJECT",
        "source_port": "bottom",
        "target_port": "bottom",
        "source_offset": -30.0,
        "cardinality_source": "||",
        "cardinality_target": "o|",
        "label_pos": 0.5,
        "waypoints": [[2950, 1140], [1950, 1140], [1950, 2120]],
        "corner_radius": 14.0,
    },

    # Cluster 6: Marketing & Campaigns
    {
        "source": "BRAND",
        "target": "AD_PACKAGE",
        "source_port": "right",
        "target_port": "left",
        "cardinality_source": "||",
        "cardinality_target": "o{",
        "label_pos": 0.5,
        "corner_radius": 8.0,
    },
    {
        "source": "AD_PACKAGE",
        "target": "AD_CAMPAIGN",
        "source_port": "right",
        "target_port": "left",
        "cardinality_source": "||",
        "cardinality_target": "o{",
        "label_pos": 0.5,
        "corner_radius": 8.0,
    },
    {
        "source": "AD_CAMPAIGN",
        "target": "SPONSORED_PRODUCT",
        "source_port": "bottom",
        "target_port": "top",
        "source_offset": -40.0,
        "cardinality_source": "||",
        "cardinality_target": "o{",
        "label_pos": 0.5,
        "waypoints": [[3450, 1530], [3115, 1530]],
        "corner_radius": 10.0,
    },
    {
        "source": "PRODUCT",
        "target": "SPONSORED_PRODUCT",
        "source_port": "bottom",
        "target_port": "top",
        "source_offset": 40.0,
        "cardinality_source": "||",
        "cardinality_target": "o{",
        "label_pos": 0.5,
        "waypoints": [[3020, 1170], [3200, 1170], [3200, 1580]],
        "corner_radius": 12.0,
    },
    {
        "source": "AD_CAMPAIGN",
        "target": "AD_RESOURCE",
        "source_port": "bottom",
        "target_port": "top",
        "cardinality_source": "||",
        "cardinality_target": "o{",
        "label_pos": 0.5,
        "corner_radius": 8.0,
    },
    {
        "source": "AD_CAMPAIGN",
        "target": "AD_CAMPAIGN_LOG",
        "source_port": "bottom",
        "target_port": "right",
        "source_offset": 50.0,
        "cardinality_source": "||",
        "cardinality_target": "o{",
        "label_pos": 0.5,
        "waypoints": [[3540, 2050]],
        "corner_radius": 10.0,
    },
    {
        "source": "MEMBER",
        "target": "AD_CAMPAIGN_LOG",
        "source_port": "bottom",
        "target_port": "bottom",
        "source_offset": -90.0,
        "cardinality_source": "||",
        "cardinality_target": "o{",
        "label_pos": 0.5,
        "waypoints": [[520, 2270], [3120, 2270]],
        "corner_radius": 14.0,
    },
]

# Write specs/master_erd_connections.json
conn_file = os.path.join(SPEC_DIR, "master_erd_connections.json")
with open(conn_file, "w", encoding="utf-8") as f:
    json.dump({"connections": connections}, f, indent=2, ensure_ascii=False)
print(f"Written: {conn_file} with {len(connections)} connections.")

# Write specs/master_erd_canvas_spec.json
canvas_spec = {
    "engine": "canvas",
    "width": 3840,
    "height": 2400,
    "scale": 1,
    "font_family": "Segoe UI, -apple-system, BlinkMacSystemFont, Arial, sans-serif",
    "font_size": 11.5,
    "bg_color": "#FFFFFF",
    "output_path": "diagram_assets/master_erd_smart_mart.png",
    "show_clusters": False,
    "clusters": clusters,
    "nodes": nodes,
    "connections_file": "specs/master_erd_connections.json",
}

spec_file = os.path.join(SPEC_DIR, "master_erd_canvas_spec.json")
with open(spec_file, "w", encoding="utf-8") as f:
    json.dump(canvas_spec, f, indent=2, ensure_ascii=False)
print(f"Written: {spec_file} with {len(nodes)} nodes, {len(clusters)} clusters, and reference to connections.")
